// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBA8FAZlu20qV_50pZ1iWnxaC6s39qILY',
    appId: '1:934422199823:web:278e9fe7e243356e66ad7a',
    messagingSenderId: '934422199823',
    projectId: 'dreams-6698d',
    authDomain: 'dreams-6698d.firebaseapp.com',
    storageBucket: 'dreams-6698d.appspot.com',
    measurementId: 'G-Q0TCD6JWZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4PwpkjWiCMe1Cebn3NpbsfmVP4VgT-s0',
    appId: '1:934422199823:android:3a7785133c75d06966ad7a',
    messagingSenderId: '934422199823',
    projectId: 'dreams-6698d',
    storageBucket: 'dreams-6698d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc_NgmhO6BX4C1MLO6tbflDxUurSUx7do',
    appId: '1:934422199823:ios:9f0c5a16192ce2ce66ad7a',
    messagingSenderId: '934422199823',
    projectId: 'dreams-6698d',
    storageBucket: 'dreams-6698d.appspot.com',
    iosClientId: '934422199823-5u50j25o2c98fa97khoog0lcbr11ha49.apps.googleusercontent.com',
    iosBundleId: 'com.example.dreams',
  );
}
